Tarefas/src/Tarefas.Web/Models/ErrorViewModel.cs
namespace Tarefas.Web.Models {

    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
    
}

Tarefas/src/Tarefas.Web/Models/TarefaViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Tarefas.Web.Models {

    public class TarefaViewModel
    {
        public int? Id { get; set; }

        [Required(ErrorMessage = "O título da tarefa deve ser preenchido.")]
        [MinLength(5, ErrorMessage = "O título deve ter no mínimo 5 caracteres.")]
        [MaxLength(100, ErrorMessage = "O título deve ter no máximo 100 caracteres.")]
        [DisplayName("Título")]    
        public string? Titulo { get; set; }        
        
        [Required(ErrorMessage = "A descrição da tarefa deve ser preenchida.")]
        [MinLength(5, ErrorMessage = "A descrição deve ter no mínimo 5 caracteres.")]
        [MaxLength(100, ErrorMessage = "A descrição deve ter no máximo 100 caracteres.")]
        [DisplayName("Descrição")]    
        public string? Descricao { get; set; }  

        [Required(ErrorMessage = "A informação de conclusão é obrigatória.")]
        [DisplayName("Concluída")]
        public bool Concluida { get; set; }
        public int UsuarioId { get; set; }

    }

}

Tarefas/src/Tarefas.Web/Models/UsuarioViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;

namespace Tarefas.Web.Models
{
    public class UsuarioViewModel
    {
        [AllowNull]
        [Required(ErrorMessage = "O Email deve ser informado.")]
        [EmailAddress(ErrorMessage = "Digite um email em formato válido.")]
        [DisplayName("Email")]    
        public string Email { get; set; }

        [AllowNull]
        [Required(ErrorMessage = "A senha deve ser informada.")]
        [DataType(DataType.Password)]
        [DisplayName("Senha")]    
        public string Senha { get; set; }
    }
}

Tarefas/src/Tarefas.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Tarefas.Web.Models;
using Microsoft.AspNetCore.Authorization;

namespace Tarefas.Web.Controllers;

[Authorize]
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }


    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Tarefas/src/Tarefas.Web/Controllers/LoginController.cs
using System;
using Tarefas.DTO;
using Tarefas.DAO;
using AutoMapper;
using Tarefas.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;


namespace Tarefas.Web.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUsuarioDAO _usuarioDAO;
        private readonly IMapper _mapper;
        public LoginController(IUsuarioDAO usuarioDAO, IMapper mapper)
        {
            _usuarioDAO = usuarioDAO;
            _mapper = mapper;
        

        }

        public IActionResult Index()
        {
            return View();
        }
            
     

        [HttpPost]
        public IActionResult Index(UsuarioViewModel usuarioViewModel)
        {

            UsuarioDTO user;

            try
            {
                user = _usuarioDAO.Autenticar(usuarioViewModel.Email, usuarioViewModel.Senha);

                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, user.Nome),
                    new Claim(ClaimTypes.Email, user.Email),
                    new Claim(ClaimTypes.PrimarySid, user.Id.ToString())
                };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                var authProperties = new AuthenticationProperties
                {
                    ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10),
                    IsPersistent = true,
                    RedirectUri = "/Login"

                };




                HttpContext.SignInAsync(
                  CookieAuthenticationDefaults.AuthenticationScheme,
                  new ClaimsPrincipal(claimsIdentity),
                      authProperties);

                return LocalRedirect("/Home");


            }
            catch (Exception ex)
            {
                AddModelError("Invallid", "Usuarios ou senha inválidos!");
                ModelState.AddModelError(string.Empty, ex.Message);
                if (ModelState.IsValid)
                {
                    return View();
                    // implementação da autenticação
                }

                return View();

                // logica de tratamento da exceção que vamos adicionar
            }

        }

        private void AddModelError(string v1, string v2)
        {
          LocalRedirect("/Login");

        }

        public IActionResult Sair()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return LocalRedirect("/Login");

        }

    }
}

Tarefas/src/Tarefas.Web/Controllers/TarefaController.cs
using Microsoft.AspNetCore.Mvc;
using Tarefas.Web.Models;
using Tarefas.DTO;
using Tarefas.DAO;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;


namespace Tarefas.Web.Controllers
{
    [Authorize]
    public class TarefaController : Controller
    {
        private readonly ITarefaDAO _tarefaDAO;

        private readonly IMapper _mapper;

        private readonly int _usuarioId;

        public TarefaController(ITarefaDAO tarefaDAO, IMapper mapper, IHttpContextAccessor httpContextAccessor)
        {
            _tarefaDAO = tarefaDAO;
            _mapper = mapper;
            _usuarioId = int.Parse(httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.PrimarySid));
        }


        public IActionResult Details(int id)
        {
            var tarefaDTO = _tarefaDAO.Consultar(id, _usuarioId);

            var TarefaViewModel = _mapper.Map<TarefaViewModel>(tarefaDTO);

            return View(TarefaViewModel);
        }

        public IActionResult Index()
        {
            var listaDeTarefasDTO = _tarefaDAO.Consultar();

            var listaDeTarefa = new List<TarefaViewModel>();

            foreach (var tarefaDTO in listaDeTarefasDTO)
            {
                listaDeTarefa.Add(_mapper.Map<TarefaViewModel>(tarefaDTO));
            }

            return View(listaDeTarefa);
        }

        public IActionResult Create()
        {
            ViewBag.UsuarioId = _usuarioId;
            return View();
        }

        [HttpPost]
        public IActionResult Create(TarefaViewModel tarefaViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var tarefaDTO = _mapper.Map<TarefaDTO>(tarefaViewModel);

            _tarefaDAO.Criar(tarefaDTO);

            return RedirectToAction("Index");
        }


        [HttpPost]
        public IActionResult Update(TarefaViewModel tarefaViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var tarefaDTO = _mapper.Map<TarefaDTO>(tarefaViewModel);

            _tarefaDAO.Atualizar(tarefaDTO);

            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            var tarefaDTO = _tarefaDAO.Consultar(id);

            var tarefaViewModel = _mapper.Map<TarefaViewModel>(tarefaDTO);

            return View(tarefaViewModel);
        }

        public IActionResult Delete(int id)
        {
            _tarefaDAO.Excluir(id);

            return RedirectToAction("Index");
        }
    }
}

Tarefas/src/Tarefas.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Tarefas/src/Tarefas.Web/Views/Login/Index.cshtml
@{
    Layout = "_Login";
}

@model Tarefas.Web.Models.UsuarioViewModel

<div class="row justify-content-md-center">
    <div class="col-md-4 g-3">
        <form method="post" class="g-3">
            <h1 class="h3 mb-3 font-weight-normal">Minhas Tarefas</h1>
            <p>Informe seu login e senha para entrar.</p>
            <hr>
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group mb-3">
                <label asp-for="Email">@Html.DisplayNameFor(model => model.Email)</label>
                <input asp-for="Email" class="form-control">
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Senha">@Html.DisplayNameFor(model => model.Senha)</label>
                <input asp-for="Senha" class="form-control">
                <span asp-validation-for="Senha" class="text-danger"></span>
            </div>            
            
            <div class="form-group mb-3">
                
                <button type="submit" class="btn btn-primary btn-block mb-4">Entrar</button>
            
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Tarefas/src/Tarefas.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tarefas.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Tarefas.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tarefas.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarefa"
                                asp-action="Index">Tarefas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarefa" asp-action="Create">Criar
                                Tarefa</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div id="user-info">
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link active" href="#">@Context!.User!.Identity!.Name</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Login" asp-action="Sair">Sair</a>
                    </li>
                </ul>
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Tarefas.Web
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Tarefas/src/Tarefas.Web/Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tarefas.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/login.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Tarefas.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</head>
<body>
    
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Tarefas/src/Tarefas.Web/Views/Tarefa/Create.cshtml
@model Tarefas.Web.Models.TarefaViewModel

<form asp-action="Create" class="row g-3">

    <h3>Nova Tarefa</h3>

    <div asp-validation-summary="All" class="text-danger"></div>

    <input asp-for="Id" hidden />

    <input asp-for="Concluida" hidden />

    <div class="col-12">
        <div class="form-group">
            <label asp-for="Titulo">@Html.DisplayNameFor(model => model.Titulo)</label>
            <input asp-for="Titulo" class="form-control" />
            <span asp-validation-for="Titulo" class="text-danger"></span>
        </div>
    </div>

    <div class="col-12">
        <div class="form-group">
            <label asp-for="Descricao">@Html.DisplayNameFor(model => model.Descricao)</label>
            <input asp-for="Descricao" class="form-control" />
            <span asp-validation-for="Descricao" class="text-danger"></span>
        </div>
    </div>

    <div class="col-12">
        <div class="form-check form-switch">
            <input type="checkbox" asp-for="Concluida" class="form-check-input" />
            <label class="form-check-label" asp-for="Concluida">@Html.DisplayNameFor(model => model.Concluida)</label>
        </div>
    </div>

    <div class="col-12">
        <input type="submit" class="btn btn-primary" /> <a class="btn btn-secondary" asp-controller="Tarefa"
            asp-action="Index">Voltar</a>
    </div>

    <input asp-for="UsuarioId" value="@ViewBag.UsuarioId" hidden />


</form>

@section Scripts
    {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Tarefas/src/Tarefas.Web/Views/Tarefa/Details.cshtml
@model Tarefas.Web.Models.TarefaViewModel

<form asp-action="Create" class="row g-3">

    <h3>Detalhes</h3>

    <input asp-for="Id" hidden />

    <input asp-for="Concluida" hidden />

    <div class="col-12">
        <div class="form-group">
            <label asp-for="Titulo">@Html.DisplayNameFor(model => model.Titulo)</label>
            <input asp-for="Titulo" class="form-control" disabled/>
        </div>
    </div>

    <div class="col-12">
        <div class="form-group">
            <label asp-for="Descricao">@Html.DisplayNameFor(model => model.Descricao)</label>
            <input asp-for="Descricao" class="form-control" disabled/>
        </div>
    </div>

     <div class="col-12">
        <div class="form-check form-switch">            
            <input type="checkbox" asp-for="Concluida" class="form-check-input" disabled/>
            <label class="form-check-label" asp-for="Concluida">@Html.DisplayNameFor(model => model.Concluida)</label>            
        </div>
    </div>

    <div class="col-12">
        <a class="btn btn-secondary" asp-controller="Tarefa" asp-action="Index">Voltar</a>
    </div>
                
</form>

Tarefas/src/Tarefas.Web/Views/Tarefa/Index.cshtml
@model IEnumerable<Tarefas.Web.Models.TarefaViewModel>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>@Html.DisplayNameFor(model => model.Titulo)</th>
            <th>@Html.DisplayNameFor(model => model.Descricao)</th>
            <th>@Html.DisplayNameFor(model => model.Concluida)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="thead-light">
                <td>@item.Titulo</td>
                <td>@item.Descricao</td>
                <td>
                    <partial name="_Status" model="item" />
                </td>
                <td style="width: 10px; white-space: nowrap;">
                    <a class="btn btn-secondary btn-sm" asp-controller="Tarefa" asp-action="Details" asp-route-id="@item.Id">Detalhes</a>
                    <a class="btn btn-secondary btn-sm" asp-controller="Tarefa" asp-action="Update" asp-route-id="@item.Id">Atualizar</a>
                    <a class="btn btn-secondary btn-sm" asp-controller="Tarefa" asp-action="Delete" asp-route-id="@item.Id">Excluir</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Tarefas/src/Tarefas.Web/Views/Tarefa/Update.cshtml
@model Tarefas.Web.Models.TarefaViewModel

<form asp-action="Update" class="row g-3">

    <h3>Edição de Tarefa</h3>

    <div asp-validation-summary="All" class="text-danger"></div>

    <input asp-for="Id" hidden />

    <div class="col-12">
        <div class="form-group">
            <label asp-for="Titulo">@Html.DisplayNameFor(model => model.Titulo)</label>
            <input asp-for="Titulo" class="form-control"/>
            <span asp-validation-for="Titulo" class="text-danger"></span>
        </div>
    </div>

    <div class="col-12">
        <div class="form-group">
            <label asp-for="Descricao">@Html.DisplayNameFor(model => model.Descricao)</label>
            <input asp-for="Descricao" class="form-control"/>
            <span asp-validation-for="Descricao" class="text-danger"></span>
        </div>
    </div>
    
    <div class="col-12">
        <div class="form-check form-switch">            
            <input type="checkbox" asp-for="Concluida" class="form-check-input"/>
            <label class="form-check-label" asp-for="Concluida">@Html.DisplayNameFor(model => model.Concluida)</label>            
        </div>
    </div>

    <div class="col-12">
        <input type="submit" class="btn btn-primary" /> <a class="btn btn-secondary" asp-controller="Tarefa" asp-action="Index">Voltar</a>
    </div>
        
</form>

@section Scripts 
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Tarefas/src/Tarefas.Web/Views/Tarefa/_Status.cshtml
@model TarefaViewModel

@if(Model.Concluida)
{
    <span><i class="bi bi-check-circle-fill"></i> Sim</span>
}
else
{
    <span><i class="bi bi-circle-fill"></i> Não</span>
}